import Head from 'next/head';
import Link from 'next/link';
import SEOSchema from '../../components/SEOSchema';
import { ARTICLES, ARTICLES_BY_SLUG } from '../../data/articles';

export async function getStaticPaths() {
  const paths = ARTICLES.map((a) => ({
    params: { slug: a.slug },
  }));
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const article = ARTICLES_BY_SLUG[params.slug] || null;
  return {
    props: { article },
  };
}

export default function ArticleDetailPage({ article }) {
  if (!article) {
    return (
      <div className="container" style={{ padding: '80px 24px', textAlign: 'center' }}>
        <h2>Article Not Found</h2>
        <p style={{ marginBottom: 24 }}>The article you are looking for does not exist or has been removed.</p>
        <Link href="/articles" className="btn btn-primary">
          Back to Articles
        </Link>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>{article.title} | Topcentral® GEO</title>
        <meta name="description" content={article.excerpt} />
        <link rel="canonical" href={`https://www.TopcentralGEO.com/articles/${article.slug}`} />
        <meta property="og:title" content={`${article.title} | Topcentral® GEO`} />
        <meta property="og:description" content={article.excerpt} />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={`https://www.TopcentralGEO.com/articles/${article.slug}`} />
      </Head>
      <SEOSchema
        type="Article"
        title={article.title}
        description={article.excerpt}
        url={`https://www.TopcentralGEO.com/articles/${article.slug}`}
        datePublished={article.date}
        author={article.author || 'Topcentral Research Team'}
      />

      <article className="container" style={{ padding: '48px 24px', maxWidth: 800, margin: '0 auto' }}>
        {/* Breadcrumb */}
        <div style={{ display: 'flex', gap: 8, marginBottom: 32, fontSize: '0.85rem', color: 'var(--text-muted)' }}>
          <Link href="/" style={{ color: 'var(--text-muted)' }}>Home</Link>
          <span>/</span>
          <Link href="/articles" style={{ color: 'var(--text-muted)' }}>Articles</Link>
          <span>/</span>
          <span style={{ color: 'var(--accent-cyan)' }}>{article.title}</span>
        </div>

        {/* Meta */}
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', marginBottom: 16, fontSize: '0.85rem', color: 'var(--text-muted)' }}>
          <span>{article.date}</span>
          <span style={{ padding: '2px 10px', borderRadius: 12, background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
            {article.category}
          </span>
          {article.tier === 'premium' && (
            <span style={{ padding: '2px 10px', borderRadius: 12, background: 'rgba(255, 171, 0, 0.1)', border: '1px solid rgba(255, 171, 0, 0.3)', color: '#ffab00' }}>
              Premium
            </span>
          )}
        </div>

        {/* Title */}
        <h1 style={{ fontSize: 'clamp(1.5rem, 3vw, 2rem)', lineHeight: 1.3, marginBottom: 20 }}>
          {article.title}
        </h1>

        {/* Author */}
        <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: 32 }}>
          By {article.author || 'Topcentral Research Team'}
        </p>

        {/* Content */}
        <div
          className="article-content"
          dangerouslySetInnerHTML={{ __html: article.content || article.excerpt }}
          style={{
            fontSize: '1rem',
            lineHeight: 1.8,
            color: 'var(--text-secondary)',
          }}
        />

        {/* Tags */}
        {article.tags && article.tags.length > 0 && (
          <div style={{ marginTop: 40, paddingTop: 24, borderTop: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {article.tags.map((tag) => (
                <Link
                  key={tag}
                  href={`/articles?tag=${encodeURIComponent(tag)}`}
                  className="tag"
                  style={{ textDecoration: 'none', fontSize: '0.8rem' }}
                >
                  #{tag}
                </Link>
              ))}
            </div>
          </div>
        )}

        {/* AIGC Attribution */}
        {article.aigcIncluded && (
          <div style={{ marginTop: 24, padding: 16, borderRadius: 'var(--radius-md)', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
            <strong style={{ color: 'var(--accent-cyan)' }}>Generated by Topcentral Agent Platform</strong>
            <p style={{ margin: '8px 0 0', fontSize: '0.8rem' }}>
              This article was generated by the Topcentral Agent Platform. Please verify key facts with a domain expert.
            </p>
          </div>
        )}

        {/* Navigation */}
        <div style={{ marginTop: 48, textAlign: 'center' }}>
          <Link href="/articles" className="btn btn-outline">
            ← Back to Articles
          </Link>
        </div>
      </article>
    </>
  );
}
